# Generated by Django 4.2.4 on 2023-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email_token',
            field=models.CharField(default=12.3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
