# Generated by Django 4.2.4 on 2023-08-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_details_email_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=122)),
                ('dataset', models.FileField(upload_to='datasets')),
                ('edafile', models.FileField(upload_to='edafiles')),
                ('final_model', models.FileField(upload_to='final_model')),
            ],
        ),
    ]
