# Generated by Django 4.2.4 on 2023-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
