# Generated by Django 4.2.4 on 2023-08-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_project_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='edafile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='final_model',
        ),
    ]
